# Flutter VR Avatar App - Analysis Options
# GPU最適化コード品質設定

include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "build/**"
    - "ios/**"
    - "android/**"
    - "assets/**"
  
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true

linter:
  rules:
    # GPU最適化 & Performance重視
    avoid_unnecessary_containers: true
    prefer_const_constructors: true
    prefer_const_declarations: true
    prefer_const_literals_to_create_immutables: true
    sized_box_for_whitespace: true
    use_full_hex_values_for_flutter_colors: true
    
    # Neural Engine & Metal API安全性
    avoid_print: false  # GPU最適化デバッグ用途で使用
    prefer_single_quotes: true
    require_trailing_commas: true
    
    # VR UI品質
    use_colored_box: true
    use_decorated_box: true
    avoid_web_libraries_in_flutter: true
    
    # Unity統合コード品質
    unnecessary_late: true
    unnecessary_null_checks: true
    avoid_redundant_argument_values: true
