# CodeMagic CI/CD Configuration
# VR Avatar App - Flutter + Unity as Library
# GPU最適化・Neural Engine対応iOS専用アプリ

workflows:
  ios-workflow:
    name: iOS VR Avatar App
    max_build_duration: 120
    instance_type: mac_mini_m1
    integrations:
      app_store_connect: codemagic
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.vr.avatar1
      vars:
        XCODE_WORKSPACE: "ios/Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
        APP_ID: 6748548295
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Set up provisioning profiles
        script: |
          # CodeMagic自動プロビジョニング
          xcode-project use-profiles
      
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      
      - name: Install CocoaPods dependencies
        script: |
          cd ios
          pod install --repo-update
      
      - name: Unity Framework の配置確認
        script: |
          # UnityFramework.framework の存在確認
          if [ ! -d "ios/Frameworks/UnityFramework.framework" ]; then
            echo "Error: UnityFramework.framework not found"
            exit 1
          fi
          echo "UnityFramework.framework found - Size: $(du -sh ios/Frameworks/UnityFramework.framework)"
      
      - name: Build iOS app
        script: |
          # GPU最適化ビルド（仕様書準拠）
          flutter build ios --release \
            --dart-define=GPU_OPTIMIZATION=true \
            --dart-define=NEURAL_ENGINE=true \
            --dart-define=METAL_API=true \
            --dart-define=TARGET_FPS=60 \
            --no-codesign
      
      - name: Build .ipa with Xcode
        script: |
          xcode-project build-ipa \
            --workspace "$XCODE_WORKSPACE" \
            --scheme "$XCODE_SCHEME" \
            --archive-flags "-destination 'generic/platform=iOS'"
    
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log
    
    publishing:
      email:
        recipients:
          - nndds@example.com
        notify:
          success: true
          failure: true
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        submit_to_app_store: false

  debug-workflow:
    name: iOS Debug Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      
      - name: Unity Framework 確認
        script: |
          ls -la ios/Frameworks/
          du -sh ios/Frameworks/UnityFramework.framework/
      
      - name: Build debug iOS
        script: |
          # デバッグビルド（開発用）
          flutter build ios --debug \
            --dart-define=GPU_OPTIMIZATION=false \
            --dart-define=DEBUG_MODE=true \
            --no-codesign
    
    artifacts:
      - build/ios/Debug-iphoneos/*.app